#version 450

layout(local_size_x = 64) in;

struct IndirectCommand {
    uint num_indices;
    uint num_instances;
    uint first_index;
    int  vertex_offset;
    uint first_instance;
};

layout(set = 0, binding = 0, std430) buffer IndirectBuffer {
    IndirectCommand indirect[];
};

layout(push_constant) uniform PC {
    uint total_batches;
};

void main() {
    uint bid = gl_GlobalInvocationID.x;
    if (bid >= total_batches) return;
    indirect[bid].num_instances = 0;
}